name: Publish to crates.io
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish_serde_with:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    # For extra security, limits to protected tags only
    environment: release
    permissions:
      # Needed to publish releases
      contents: write
      # Required for OIDC token exchange
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "Install/Update the Rust version"
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
          cargo --version
          rustc --version
      - name: Get version from tag
        id: tag_name
        run: echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@1faaf50aa09d5793d9a100819973df801febfb31 # v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./serde_with/CHANGELOG.md
      - name: Create Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the "Get Changelog Entry" step above, referencing its ID to get its `outputs` object.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          tag_name: "v${{ steps.changelog_reader.outputs.version }}"
          name: "serde_with v${{ steps.changelog_reader.outputs.version }}"
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
      - uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1
        id: auth
      # The programs wait until the package is in the index.
      - run: cargo publish --package serde_with_macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - run: cargo publish --package serde_with
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
